version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - proxy
    volumes:
      - wwebjs_cache:/path/to/wwebjs_cache
      - wwebjs_auth:/path/to/wwebjs_auth

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge

volumes:
  wwebjs_cache:
  wwebjs_auth: